name: Run Python scripts

on:
  schedule:
    - cron: '0 5 * * 2'  # This will run at 5:00 AM UTC every Tuesday
    - cron: '0 5 * * 4'  # This will run at 5:00 AM UTC every Thursday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run train_pipeline.py
      run: python train_pipeline.py
      if: github.event.schedule == '0 5 * * 2'

    - name: Run pred_pipeline.py
      run: python pred_pipeline.py
      if: github.event.schedule == '0 5 * * 4'