name: Run train_pipeline.py

on:
  schedule:
    - cron: '0 16 * * 3'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run train_pipeline.py
      run: |
        python train_pipeline.py
        git config --global user.name 'Drake Weissman'
        git config --global user.email 'drakeweissman@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/drakeweissman/fantasy.git
        git add pickle_files/*.pickle
        git commit -m "Add new pickle file"
        git push