name: Run train_pipeline.py

on:
  schedule:
    - cron: '30 23 * * 2' # This will run at 11:30 PM UTC (6:30 PM EST) every Tuesday
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run train_pipeline.py
      run: python train_pipeline.py