name: Run train_pipeline.py

on:
  schedule:
    - cron: '30 17 * * 3'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run train_pipeline.py
      run: |
        python train_pipeline.py
        git config --global user.name 'Drake Weissman'
        git config --global user.email 'drakeweissman@gmail.com'
        git add pickle_files/*.pickle
        git commit -m "Add new pickle file"
        git push